a = <<~HEREDOC
<div class="entry unvoted"><p class="tagline"><a href="javascript:void(0)" class="expand" onclick="return togglecomment(this)">[–]</a><a href="https://www.reddit.com/user/FlashJordanK" class="author may-blank id-t2_a5xp9">FlashJordanK</a><span class="flair flair-noflair" title=""></span><span class="userattrs"></span> <span class="score dislikes" title="22">22 points</span><span class="score unvoted" title="23">23 points</span><span class="score likes" title="24">24 points</span> <time title="Mon Oct 16 14:50:51 2017 UTC" datetime="2017-10-16T14:50:51+00:00" class="live-timestamp">18 hours ago</time>&nbsp;<a href="javascript:void(0)" class="numchildren" onclick="return togglecomment(this)">(2 children)</a></p><form action="#" class="usertext warn-on-unload" onsubmit="return post_form(this, 'editusertext')" id="form-t1_dog09r2em3"><input type="hidden" name="thing_id" value="t1_dog09r2"><div class="usertext-body may-blank-within md-container "><div class="md"><p>Bitcoin This is huge news. People have been talking about interledger protocol as a method to bank the unbanked for a few years now. The Gates Foundation partnering with ripple may actually see this happen sooner of later. Amazing for XRP hodlers, crypto-investors as a whole, but most importantly, for humanity! </p>

<p>Well done guys!</p>
</div>
</div></form><ul class="flat-list buttons"><li class="first"><a href="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog09r2/" data-inbound-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog09r2/?utm_content=permalink&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=CryptoCurrency" data-href-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog09r2/" data-event-action="permalink" class="bylink" rel="nofollow">permalink</a></li><li><a href="javascript:void(0)" data-comment="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog09r2/" data-media="www.redditmedia.com" data-link="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/" data-root="true" data-title="Ripple &amp; the Gates Foundation Team Up to Level the Economic Playing Field for the Poo" class="embed-comment">embed</a></li><li class="comment-save-button save-button"><a href="javascript:void(0)">save</a></li><li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li><li class="give-gold-button"><a href="/gold?goldtype=gift&amp;months=1&amp;thing=t1_dog09r2" title="give reddit gold in appreciation of this post." class="give-gold login-required access-required" data-event-action="gild">give gold</a></li><li class="reply-button"><a class="access-required" href="javascript:void(0)" data-event-action="comment" onclick="return reply(this)">reply</a></li></ul><div class="reportform report-t1_dog09r2"></div></div>
HEREDOC

b = <<~HEREDOC
<div class="entry unvoted"><p class="tagline"><a href="javascript:void(0)" class="expand" onclick="return togglecomment(this)">[–]</a><a href="https://www.reddit.com/user/dobbelDK" class="author may-blank id-t2_277nqht">dobbelDK</a><span class="flair flair-New" title="Redditor for &lt; 1 hour.">Redditor for &lt; 1 hour.</span><span class="userattrs"></span> <span class="score-hidden" title="this subreddit hides comment scores for 5 minutes">[score hidden]</span> <time title="Tue Oct 17 08:39:50 2017 UTC" datetime="2017-10-17T08:39:50+00:00" class="live-timestamp">just now</time>&nbsp;<a href="javascript:void(0)" class="numchildren" onclick="return togglecomment(this)">(0 children)</a></p><form action="#" class="usertext warn-on-unload" onsubmit="return post_form(this, 'editusertext')" id="form-t1_dohcuy5rd7"><input type="hidden" name="thing_id" value="t1_dohcuy5"><div class="usertext-body may-blank-within md-container "><div class="md"><p>Bitcoin Just wanted to share this with you all.. </p>

<p>If you haven't heard about Aurora Mine which just has launched, it is a super cool platform where you can get 100 GH/s for free to mine bitcoins. Basically, you just have to sign up and then it starts mining... And you can pay out with no fees. It won't be free for long.. However, you can also put in investments to gain more computerpower! I really like what I see from them so far.. So check it out!</p>

<p>Check it out: <a href="https://www.auroramine.com/?ref=363868" rel="nofollow">https://www.auroramine.com/?ref=363868</a></p>
</div>
</div></form><ul class="flat-list buttons"><li class="first"><a href="https://www.reddit.com/r/CryptoCurrency/comments/76woae/daily_general_discussion_october_17_2017/dohcuy5/" data-inbound-url="/r/CryptoCurrency/comments/76woae/daily_general_discussion_october_17_2017/dohcuy5/?utm_content=permalink&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=CryptoCurrency" data-href-url="/r/CryptoCurrency/comments/76woae/daily_general_discussion_october_17_2017/dohcuy5/" data-event-action="permalink" class="bylink" rel="nofollow">permalink</a></li><li><a href="javascript:void(0)" data-comment="/r/CryptoCurrency/comments/76woae/daily_general_discussion_october_17_2017/dohcuy5/" data-media="www.redditmedia.com" data-link="/r/CryptoCurrency/comments/76woae/daily_general_discussion_october_17_2017/" data-root="true" data-title="Daily General Discussion - October 17, 2017" class="embed-comment">embed</a></li><li class="comment-save-button save-button"><a href="javascript:void(0)">save</a></li><li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li><li class="give-gold-button"><a href="/gold?goldtype=gift&amp;months=1&amp;thing=t1_dohcuy5" title="give reddit gold in appreciation of this post." class="give-gold login-required access-required" data-event-action="gild">give gold</a></li><li class="reply-button"><a class="access-required" href="javascript:void(0)" data-event-action="comment" onclick="return reply(this)">reply</a></li></ul><div class="reportform report-t1_dohcuy5"></div></div>
HEREDOC

c = <<~HEREDOC
<div class="entry unvoted"><p class="tagline"><a href="javascript:void(0)" class="expand" onclick="return togglecomment(this)">[–]</a><a href="https://www.reddit.com/user/Rhaeguarco" class="author may-blank id-t2_zcwac">Rhaeguarco</a><span class="flair flair-noflair" title=""></span><span class="userattrs"></span> <span class="score dislikes" title="14">14 points</span><span class="score unvoted" title="15">15 points</span><span class="score likes" title="16">16 points</span> <time title="Mon Oct 16 15:38:59 2017 UTC" datetime="2017-10-16T15:38:59+00:00" class="live-timestamp">17 hours ago</time>&nbsp;<a href="javascript:void(0)" class="numchildren" onclick="return togglecomment(this)">(17 children)</a></p><form action="#" class="usertext warn-on-unload" onsubmit="return post_form(this, 'editusertext')" id="form-t1_dog2sddkec"><input type="hidden" name="thing_id" value="t1_dog2sdd"><div class="usertext-body may-blank-within md-container "><div class="md"><p>Bitcoin Oh, but I thought this subreddit thought XRP was a "shitcoin"? Fools. First it's Stellar Lumens, now it's Ripple. Never trust the idiotic herd mentality of this subreddit.</p>

<p>Sheep.</p>
</div>
</div></form><ul class="flat-list buttons"><li class="first"><a href="https://www.reddit.com/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog2sdd/" data-inbound-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog2sdd/?utm_content=permalink&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=CryptoCurrency" data-href-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog2sdd/" data-event-action="permalink" class="bylink" rel="nofollow">permalink</a></li><li><a href="javascript:void(0)" data-comment="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/dog2sdd/" data-media="www.redditmedia.com" data-link="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/" data-root="true" data-title="Ripple &amp; the Gates Foundation Team Up to Level the Economic Playing Field for the Poo" class="embed-comment">embed</a></li><li class="comment-save-button save-button"><a href="javascript:void(0)">save</a></li><li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li><li class="give-gold-button"><a href="/gold?goldtype=gift&amp;months=1&amp;thing=t1_dog2sdd" title="give reddit gold in appreciation of this post." class="give-gold login-required access-required" data-event-action="gild">give gold</a></li><li class="reply-button"><a class="access-required" href="javascript:void(0)" data-event-action="comment" onclick="return reply(this)">reply</a></li></ul><div class="reportform report-t1_dog2sdd"></div></div>
HEREDOC

d = <<~HEREDOC
<div class="entry unvoted"><p class="tagline"><a href="javascript:void(0)" class="expand" onclick="return togglecomment(this)">[–]</a><a href="https://www.reddit.com/user/the-rooster" class="author may-blank id-t2_12zs4l">the-rooster</a><span class="flair flair-noflair" title=""></span><span class="userattrs"></span> <span class="score dislikes" title="-3">-3 points</span><span class="score unvoted" title="-2">-2 points</span><span class="score likes" title="-1">-1 points</span> <time title="Mon Oct 16 17:50:51 2017 UTC" datetime="2017-10-16T17:50:51+00:00" class="live-timestamp">15 hours ago</time>&nbsp;<a href="javascript:void(0)" class="numchildren" onclick="return togglecomment(this)">(0 children)</a></p><form action="#" class="usertext warn-on-unload" onsubmit="return post_form(this, 'editusertext')" id="form-t1_doga5ap32o"><input type="hidden" name="thing_id" value="t1_doga5ap"><div class="usertext-body may-blank-within md-container "><div class="md"><p>Bitcoin I have 25% of my crypto portfolio in XRP but this announcement is pretty shit.</p>
</div>
</div></form><ul class="flat-list buttons"><li class="first"><a href="https://www.reddit.com/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/doga5ap/" data-inbound-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/doga5ap/?utm_content=permalink&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=CryptoCurrency" data-href-url="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/doga5ap/" data-event-action="permalink" class="bylink" rel="nofollow">permalink</a></li><li><a href="javascript:void(0)" data-comment="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/doga5ap/" data-media="www.redditmedia.com" data-link="/r/CryptoCurrency/comments/76qhi2/ripple_the_gates_foundation_team_up_to_level_the/" data-root="true" data-title="Ripple &amp; the Gates Foundation Team Up to Level the Economic Playing Field for the Poo" class="embed-comment">embed</a></li><li class="comment-save-button save-button"><a href="javascript:void(0)">save</a></li><li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li><li class="give-gold-button"><a href="/gold?goldtype=gift&amp;months=1&amp;thing=t1_doga5ap" title="give reddit gold in appreciation of this post." class="give-gold login-required access-required" data-event-action="gild">give gold</a></li><li class="reply-button"><a class="access-required" href="javascript:void(0)" data-event-action="comment" onclick="return reply(this)">reply</a></li></ul><div class="reportform report-t1_doga5ap"></div></div>
HEREDOC

e = <<~HEREDOC
<div class="entry unvoted"><p class="tagline"><a href="javascript:void(0)" class="expand" onclick="return togglecomment(this)">[–]</a><a href="https://www.reddit.com/user/soul5tice" class="author may-blank id-t2_akm0l">soul5tice</a><span class="flair flair-noflair" title=""></span><span class="userattrs"></span> <span class="score dislikes" title="0">0 points</span><span class="score unvoted" title="1">1 point</span><span class="score likes" title="2">2 points</span> <time title="Tue Oct 17 04:38:31 2017 UTC" datetime="2017-10-17T04:38:31+00:00" class="live-timestamp">4 hours ago</time>&nbsp;<a href="javascript:void(0)" class="numchildren" onclick="return togglecomment(this)">(0 children)</a></p><form action="#" class="usertext warn-on-unload" onsubmit="return post_form(this, 'editusertext')" id="form-t1_doh6o87zv1"><input type="hidden" name="thing_id" value="t1_doh6o87"><div class="usertext-body may-blank-within md-container "><div class="md"><p>bitcoin moon mission 2018</p>
</div>
</div></form><ul class="flat-list buttons"><li class="first"><a href="https://www.reddit.com/r/CryptoCurrency/comments/76ukc7/brace_yourself_wall_street_big_money_and/doh6o87/" data-inbound-url="/r/CryptoCurrency/comments/76ukc7/brace_yourself_wall_street_big_money_and/doh6o87/?utm_content=permalink&amp;utm_medium=front&amp;utm_source=reddit&amp;utm_name=CryptoCurrency" data-href-url="/r/CryptoCurrency/comments/76ukc7/brace_yourself_wall_street_big_money_and/doh6o87/" data-event-action="permalink" class="bylink" rel="nofollow">permalink</a></li><li><a href="javascript:void(0)" data-comment="/r/CryptoCurrency/comments/76ukc7/brace_yourself_wall_street_big_money_and/doh6o87/" data-media="www.redditmedia.com" data-link="/r/CryptoCurrency/comments/76ukc7/brace_yourself_wall_street_big_money_and/" data-root="true" data-title="Brace yourself: Wall Street big money (and government regulators) are coming..." class="embed-comment">embed</a></li><li class="comment-save-button save-button"><a href="javascript:void(0)">save</a></li><li class="report-button login-required"><a href="javascript:void(0)" class="reportbtn access-required" data-event-action="report">report</a></li><li class="give-gold-button"><a href="/gold?goldtype=gift&amp;months=1&amp;thing=t1_doh6o87" title="give reddit gold in appreciation of this post." class="give-gold login-required access-required" data-event-action="gild">give gold</a></li><li class="reply-button"><a class="access-required" href="javascript:void(0)" data-event-action="comment" onclick="return reply(this)">reply</a></li></ul><div class="reportform report-t1_doh6o87"></div></div>
HEREDOC

EXAMPLE_COMMENTS = [a, b, c, d, e]
